"use server";

/**
 * lib/journey-content/assessment-actions.ts
 *
 * Server action that records a user's structured answer to an
 * assessment-kind journey item. Phase 3 step 2.
 *
 * Architecture:
 *   - The same `journey_item_responses` table holds responses for
 *     content items (text only) and for assessments (structured
 *     answer in `structured_answer` jsonb, optional summary text in
 *     `response_text`).
 *   - The submission is also marked as a completion in
 *     `journey_item_completions` so the rail / work-area treat the
 *     assessment as "done" and move on.
 *
 * Hard rules:
 *   - Auth: session client. RLS already restricts the user to their
 *     own scheduled items (migration 035).
 *   - Idempotent: submitting twice updates the previous response
 *     instead of creating a duplicate. We use upsert keyed on
 *     (scheduled_item_id, user_id).
 *   - Never throws to the caller.
 */

import { createServerSupabaseClient } from "@/lib/supabase/server";
import { computeResponseTags } from "@/lib/dashboard/auto-tag";

export type AssessmentSubmitResult =
  | { ok: true; responseId: string }
  | { ok: false; reason: "unauthenticated" | "invalid_input" | "db_error"; message?: string };

export async function submitAssessmentResponse(args: {
  scheduledItemId: string;
  /** Map of question.id → answer. Shape varies per question kind:
   *    single_choice  → string (option key)
   *    multiple_choice → string[]
   *    scale          → number
   *    open_text      → string
   *    ranking        → string[] (ordered keys)
   */
  answers: Record<string, unknown>;
  /** Optional one-line summary the user typed in addition to the
   *  structured answers. Stored in response_text. */
  summaryText?: string;
  isPrivate?: boolean;
}): Promise<AssessmentSubmitResult> {
  const supabase = await createServerSupabaseClient();

  const {
    data: { user },
  } = await supabase.auth.getUser();
  if (!user) return { ok: false, reason: "unauthenticated" };

  const scheduledItemId = String(args.scheduledItemId ?? "").trim();
  if (!scheduledItemId) {
    return { ok: false, reason: "invalid_input", message: "missing scheduled_item_id" };
  }

  const answers = args.answers;
  if (!answers || typeof answers !== "object") {
    return { ok: false, reason: "invalid_input", message: "answers must be an object" };
  }
  if (Object.keys(answers).length === 0) {
    return { ok: false, reason: "invalid_input", message: "answers cannot be empty" };
  }

  const summaryText = String(args.summaryText ?? "").trim();
  // We always need SOMETHING in response_text - DB requires it not-empty.
  // Default to an autogenerated placeholder when the user didn't type anything.
  const responseText =
    summaryText.length > 0
      ? summaryText
      : "[אבחון מלא - מובנה בלבד]"; // "Structured-only response"

  // Try insert first; on unique-conflict fall back to update.
  // (We don't have a unique index on (scheduled_item_id, user_id) yet;
  // for now we soft-handle by checking for existing row first.)
  const { data: existing } = await supabase
    .from("journey_item_responses")
    .select("id")
    .eq("scheduled_item_id", scheduledItemId)
    .eq("user_id", user.id)
    .order("created_at", { ascending: false })
    .limit(1)
    .maybeSingle();

  // Phase 4 - auto-tags. Pass hasStructuredAnswer=true so the
  // clinician CRM can filter assessment-kind responses cheaply.
  const tags = computeResponseTags({
    text: summaryText,
    isPrivate: args.isPrivate === true,
    hasStructuredAnswer: true,
  });

  let responseId: string | null = null;

  if (existing?.id) {
    // Update the existing response - the user is revising.
    const { data: upd, error: updErr } = await supabase
      .from("journey_item_responses")
      .update({
        response_text: responseText,
        structured_answer: answers,
        is_private: args.isPrivate === true,
        tags,
      })
      .eq("id", existing.id)
      .select("id")
      .single();
    if (updErr) {
      console.error("[submitAssessmentResponse] update failed", updErr);
      return { ok: false, reason: "db_error", message: updErr.message };
    }
    responseId = String(upd.id);
  } else {
    const { data: ins, error: insErr } = await supabase
      .from("journey_item_responses")
      .insert({
        scheduled_item_id: scheduledItemId,
        user_id: user.id,
        response_text: responseText,
        structured_answer: answers,
        is_private: args.isPrivate === true,
        tags,
      })
      .select("id")
      .single();
    if (insErr) {
      console.error("[submitAssessmentResponse] insert failed", insErr);
      return { ok: false, reason: "db_error", message: insErr.message };
    }
    responseId = String(ins.id);
  }

  // Best-effort completion record - the rail uses this to show "done".
  // If it fails we still consider the response saved.
  try {
    await supabase.from("journey_item_completions").upsert(
      {
        scheduled_item_id: scheduledItemId,
        completed_by: user.id,
      },
      { onConflict: "scheduled_item_id" },
    );
  } catch (e) {
    console.warn("[submitAssessmentResponse] completion upsert failed (non-fatal)", e);
  }

  return { ok: true, responseId: responseId ?? "" };
}
