-- 085_cms_texts_about_founder.sql
--
-- Seed CMS rows for the /[locale]/about/founder editorial page.
--
-- Until now this route had its copy hard-coded inside
-- app/[locale]/about/founder/page.tsx (Hebrew-only, with a small set
-- of bilingual chrome strings). This migration:
--
--   1. Adds `about` as a CMS page bucket — the matching `CMS_PAGES`
--      enum entry lives in lib/cms/types.ts.
--   2. Inserts one row per editable string under `about.founder.*`,
--      grouped into sections (meta / hero / chapter1..8 / cta / footer)
--      that the admin UI uses as the tab grouping inside the page tab.
--   3. Flags `hero.nameRich`, `chapter4.p2`, `chapter7.closer` as
--      `is_rich = true` because their Hebrew defaults already contain
--      `<em>` markup (the brand-accent italic word).
--
-- All INSERTs are gated on `ON CONFLICT (key) DO NOTHING` so re-running
-- this migration on a database where rows already exist is a no-op —
-- no admin edits get clobbered.
--
-- Bilingual coverage notes:
--   • The founder page is intentionally Hebrew-only for the long-form
--     story copy (see comment block at the top of page.tsx). The
--     English column on those rows carries the same Hebrew text so
--     /en/about/founder continues to render the story as it always
--     has. A future English translation pass will edit `en_text`
--     from /admin/content without a deploy.
--   • The bilingual chrome rows (backLink, eyebrow, bioMeta, imageAlt,
--     cta.button, meta.title, meta.description) carry distinct
--     English text matching what the page already renders today.

BEGIN;

INSERT INTO public.cms_texts (key, page, section, he_text, en_text, is_rich)
VALUES
  -- ── Meta (page <head>) ─────────────────────────────────────────────
  ('about.founder.meta.title',
   'about', 'meta',
   'איציק ברלב - הסיפור שמאחורי מיאושי',
   'Itzik Berlev - The Story Behind Mioshy',
   false),
  ('about.founder.meta.description',
   'about', 'meta',
   'המסע האישי של איציק ברלב, מייסד מיאושי - מהמשבר הזוגי שכמעט פירק את הנישואים, דרך 600 ספרים בשלוש שפות, ועד למיאושי. הסיפור שיכול להיות גם שלכם.',
   'The personal journey of Itzik Berlev, Mioshy''s founder - from a near-breakup, through 600 books in three languages, to founding Mioshy. A story that could be yours too.',
   false),

  -- ── Hero (top of page) ─────────────────────────────────────────────
  ('about.founder.hero.backLink',
   'about', 'hero',
   'חזרה למיאושי',
   'Back to Mioshy',
   false),
  ('about.founder.hero.eyebrow',
   'about', 'hero',
   'הסיפור שמאחורי מיאושי',
   'The story behind Mioshy',
   false),
  ('about.founder.hero.nameRich',
   'about', 'hero',
   'איציק <em>ברלב</em>',
   'Itzik <em>Berlev</em>',
   true),
  ('about.founder.hero.bioMeta',
   'about', 'hero',
   'בן 45 · נשוי 17 שנה · אבא לליאן (16), נדב (14) ונועם (7) · מייסד מיאושי',
   '45 · Married 17 years · Father to Lian, Nadav and Noam · Founder of Mioshy',
   false),
  ('about.founder.hero.imageAlt',
   'about', 'hero',
   'איציק ברלב',
   'Itzik Berlev',
   false),
  ('about.founder.hero.pullQuote',
   'about', 'hero',
   'פעם חשבנו להתפרק. היום אני בונה משחקים שמחזירים לאלפי זוגות את התשוקה שאיבדו.',
   'פעם חשבנו להתפרק. היום אני בונה משחקים שמחזירים לאלפי זוגות את התשוקה שאיבדו.',
   false),

  -- ── Chapter 1: The crisis ──────────────────────────────────────────
  ('about.founder.chapter1.title',
   'about', 'chapter1',
   'הרגע שכמעט פירק אותנו',
   'הרגע שכמעט פירק אותנו',
   false),
  ('about.founder.chapter1.lede',
   'about', 'chapter1',
   'כמו אצל הרבה זוגות, גם אצלנו זה התחיל בלי דרמה. הילדים עוד היו קטנים, החיים זזו מהר, ואיכשהו, באיזשהו רגע, הבטנו אחת בשני וכבר לא זיהינו את עצמנו.',
   'כמו אצל הרבה זוגות, גם אצלנו זה התחיל בלי דרמה. הילדים עוד היו קטנים, החיים זזו מהר, ואיכשהו, באיזשהו רגע, הבטנו אחת בשני וכבר לא זיהינו את עצמנו.',
   false),
  ('about.founder.chapter1.p1',
   'about', 'chapter1',
   'השגרה הצמיחה רגליים. עבודה, גן, ארוחות ערב, הרדמת ילדים, שינה. ובסוף השבוע - אותו דבר. כשניסינו להזכר מתי בפעם האחרונה צחקנו ביחד עד דמעות, באמת לא ידענו לענות.',
   'השגרה הצמיחה רגליים. עבודה, גן, ארוחות ערב, הרדמת ילדים, שינה. ובסוף השבוע - אותו דבר. כשניסינו להזכר מתי בפעם האחרונה צחקנו ביחד עד דמעות, באמת לא ידענו לענות.',
   false),
  ('about.founder.chapter1.p2',
   'about', 'chapter1',
   'כששיחה אחת לא הספיקה, פנינו לייעוץ זוגי. כשגם זה לא היה מספיק, הוספנו סקסולוגית. ישבנו מול אנשים מקצועיים, דיברנו, בכינו, ניסינו.',
   'כששיחה אחת לא הספיקה, פנינו לייעוץ זוגי. כשגם זה לא היה מספיק, הוספנו סקסולוגית. ישבנו מול אנשים מקצועיים, דיברנו, בכינו, ניסינו.',
   false),
  ('about.founder.chapter1.p3',
   'about', 'chapter1',
   'וזה לא עזר.',
   'וזה לא עזר.',
   false),

  -- ── Chapter 2: The decision ────────────────────────────────────────
  ('about.founder.chapter2.title',
   'about', 'chapter2',
   'ההחלטה - לקחת את זה לידיים',
   'ההחלטה - לקחת את זה לידיים',
   false),
  ('about.founder.chapter2.p1',
   'about', 'chapter2',
   'הייתי יכול להמשיך לחפש מטפל אחר, גישה אחרת, איזשהו פתרון מבחוץ. במקום זה, החלטתי משהו אחר: אם אף אחד לא הולך להציל את הזוגיות שלנו - אני אעשה את זה בעצמי.',
   'הייתי יכול להמשיך לחפש מטפל אחר, גישה אחרת, איזשהו פתרון מבחוץ. במקום זה, החלטתי משהו אחר: אם אף אחד לא הולך להציל את הזוגיות שלנו - אני אעשה את זה בעצמי.',
   false),
  ('about.founder.chapter2.p2',
   'about', 'chapter2',
   'הפסקתי לחכות לתשובות. התחלתי לחפש אותן. מה השתבש בדרך? איפה איבדנו אחד את השני? והכי חשוב - האם בכלל אפשר לחזור?',
   'הפסקתי לחכות לתשובות. התחלתי לחפש אותן. מה השתבש בדרך? איפה איבדנו אחד את השני? והכי חשוב - האם בכלל אפשר לחזור?',
   false),
  ('about.founder.chapter2.p3',
   'about', 'chapter2',
   'ידעתי שזה לא ייפתר בסוף שבוע ארוך. אם אני רוצה לראות שוב את אושרת כפי שראיתי אותה כשהכרתי אותה - אצטרך ללכת עם זה עד הסוף.',
   'ידעתי שזה לא ייפתר בסוף שבוע ארוך. אם אני רוצה לראות שוב את אושרת כפי שראיתי אותה כשהכרתי אותה - אצטרך ללכת עם זה עד הסוף.',
   false),

  -- ── Chapter 3: The study ───────────────────────────────────────────
  ('about.founder.chapter3.title',
   'about', 'chapter3',
   'מאות ספרים. שלוש שפות.',
   'מאות ספרים. שלוש שפות.',
   false),
  ('about.founder.chapter3.p1',
   'about', 'chapter3',
   'התחלתי לקרוא. בעברית, באנגלית, ובאיטלקית - שלוש שפות, מאות ספרים. זוגיות, תשוקה, אהבה, פסיכולוגיה, סקסולוגיה. כל מה שמצאתי, קראתי. בלילות, אחרי שהילדים נרדמו, בנסיעות לעבודה, בכל חור של זמן.',
   'התחלתי לקרוא. בעברית, באנגלית, ובאיטלקית - שלוש שפות, מאות ספרים. זוגיות, תשוקה, אהבה, פסיכולוגיה, סקסולוגיה. כל מה שמצאתי, קראתי. בלילות, אחרי שהילדים נרדמו, בנסיעות לעבודה, בכל חור של זמן.',
   false),
  ('about.founder.chapter3.p2',
   'about', 'chapter3',
   'לא הסתפקתי בספרים. נרשמתי לקורסים - ייעוץ זוגי, NLP, סקסולוגיה. רציתי שיהיה לי גם הידע התיאורטי וגם הכלים המעשיים. רציתי להבין את זה כל הדרך עד הסוף.',
   'לא הסתפקתי בספרים. נרשמתי לקורסים - ייעוץ זוגי, NLP, סקסולוגיה. רציתי שיהיה לי גם הידע התיאורטי וגם הכלים המעשיים. רציתי להבין את זה כל הדרך עד הסוף.',
   false),
  ('about.founder.chapter3.pullQuote',
   'about', 'chapter3',
   'לא חיפשתי תיאוריה. חיפשתי תרופה.',
   'לא חיפשתי תיאוריה. חיפשתי תרופה.',
   false),
  ('about.founder.chapter3.p3',
   'about', 'chapter3',
   'וככל שצללתי עמוק יותר, התחלתי לראות שהסיפור שלנו לא יוצא דופן. זוגות נופלים שוב ושוב לאותן המלכודות. אבל גיליתי גם משהו אחר - שיש דרכים אחרות לצאת מהן. לא דרך הספה אצל המטפל, ולא דרך לילות של בכי. דרכים שמרגישות אחרת לגמרי. קלות יותר. חמות יותר. ביחד.',
   'וככל שצללתי עמוק יותר, התחלתי לראות שהסיפור שלנו לא יוצא דופן. זוגות נופלים שוב ושוב לאותן המלכודות. אבל גיליתי גם משהו אחר - שיש דרכים אחרות לצאת מהן. לא דרך הספה אצל המטפל, ולא דרך לילות של בכי. דרכים שמרגישות אחרת לגמרי. קלות יותר. חמות יותר. ביחד.',
   false),

  -- ── Chapter 4: The breakthrough ────────────────────────────────────
  ('about.founder.chapter4.title',
   'about', 'chapter4',
   'הרגע שהבנתי שזה עובד',
   'הרגע שהבנתי שזה עובד',
   false),
  ('about.founder.chapter4.p1',
   'about', 'chapter4',
   'התוצאה לא איחרה לבוא. החזרנו את התשוקה. את המבטים מעבר לחדר. את הצחוק שקיים רק בין שני אנשים שבחרו אחד בשני, וזוכרים בדיוק למה.',
   'התוצאה לא איחרה לבוא. החזרנו את התשוקה. את המבטים מעבר לחדר. את הצחוק שקיים רק בין שני אנשים שבחרו אחד בשני, וזוכרים בדיוק למה.',
   false),
  ('about.founder.chapter4.p2',
   'about', 'chapter4',
   'לא היה רגע אחד דרמטי. היה תהליך. אבל בנקודה מסוימת הסתכלתי על אושרת והבנתי שמשהו השתנה - אנחנו שוב <em>אנחנו</em>. וכל מה שעברנו עד אז לא היה הסוף - הוא היה התחלה חדשה.',
   'לא היה רגע אחד דרמטי. היה תהליך. אבל בנקודה מסוימת הסתכלתי על אושרת והבנתי שמשהו השתנה - אנחנו שוב <em>אנחנו</em>. וכל מה שעברנו עד אז לא היה הסוף - הוא היה התחלה חדשה.',
   true),

  -- ── Chapter 5: Why games ───────────────────────────────────────────
  ('about.founder.chapter5.title',
   'about', 'chapter5',
   'למה דווקא משחקים',
   'למה דווקא משחקים',
   false),
  ('about.founder.chapter5.p1',
   'about', 'chapter5',
   'תמיד אהבתי משחקים. את הדרך שבה הם פותחים שיחות שלעולם לא היו נפתחות אחרת. את האופן שבו הם מאפשרים להיות פגיעים בלי להרגיש מאוימים. את זה שבמשחק, מותר לשאול מה שלא היית מעז לשאול בארוחת ערב.',
   'תמיד אהבתי משחקים. את הדרך שבה הם פותחים שיחות שלעולם לא היו נפתחות אחרת. את האופן שבו הם מאפשרים להיות פגיעים בלי להרגיש מאוימים. את זה שבמשחק, מותר לשאול מה שלא היית מעז לשאול בארוחת ערב.',
   false),
  ('about.founder.chapter5.p2',
   'about', 'chapter5',
   'ברגע שחיברתי בין הידע שצברתי לבין האהבה הזאת - הבנתי שיש פה משהו. התחלתי ליצור משחקים. בהתחלה רק לאושרת ולי. אחר-כך לחברים קרובים - אלה שראיתי אצלם את אותם הדפוסים שהיו אצלנו. הם עבדו. שם, בסלון, על השולחן בארוחת ערב - הם פשוט עבדו.',
   'ברגע שחיברתי בין הידע שצברתי לבין האהבה הזאת - הבנתי שיש פה משהו. התחלתי ליצור משחקים. בהתחלה רק לאושרת ולי. אחר-כך לחברים קרובים - אלה שראיתי אצלם את אותם הדפוסים שהיו אצלנו. הם עבדו. שם, בסלון, על השולחן בארוחת ערב - הם פשוט עבדו.',
   false),
  ('about.founder.chapter5.p3',
   'about', 'chapter5',
   'וזה היה הרגע שבו הבנתי שאני לא יכול לשמור את זה לעצמי.',
   'וזה היה הרגע שבו הבנתי שאני לא יכול לשמור את זה לעצמי.',
   false),

  -- ── Chapter 6: The founding ────────────────────────────────────────
  ('about.founder.chapter6.title',
   'about', 'chapter6',
   'ככה נולדה מיאושי',
   'ככה נולדה מיאושי',
   false),
  ('about.founder.chapter6.p1',
   'about', 'chapter6',
   'עם הידע שצברתי, עם האהבה שלי למשחקים, ועם ההבנה שזה באמת עובד - התחלתי לבנות משהו גדול יותר. מקום שיתן לזוגות אחרים את אותם הכלים בדיוק שעזרו לנו, בלי שיצטרכו לעבור את הדרך הארוכה שאני עברתי.',
   'עם הידע שצברתי, עם האהבה שלי למשחקים, ועם ההבנה שזה באמת עובד - התחלתי לבנות משהו גדול יותר. מקום שיתן לזוגות אחרים את אותם הכלים בדיוק שעזרו לנו, בלי שיצטרכו לעבור את הדרך הארוכה שאני עברתי.',
   false),
  ('about.founder.chapter6.p2',
   'about', 'chapter6',
   'ככה נולדה מיאושי. בית - יצירתי, חם, חכם, ועם מטרה אחת ברורה: להחזיר לזוגיות את הרוח שלה. המשחקים שפיתחתי לאורך השנים מובילים אתכם למסע שמחבר אתכם מחדש - בתקשורת, בתשוקה, באינטימיות. אנחנו לא בקדמת הבמה. אנחנו ברקע, מלווים. צעד אחר צעד.',
   'ככה נולדה מיאושי. בית - יצירתי, חם, חכם, ועם מטרה אחת ברורה: להחזיר לזוגיות את הרוח שלה. המשחקים שפיתחתי לאורך השנים מובילים אתכם למסע שמחבר אתכם מחדש - בתקשורת, בתשוקה, באינטימיות. אנחנו לא בקדמת הבמה. אנחנו ברקע, מלווים. צעד אחר צעד.',
   false),
  ('about.founder.chapter6.p3',
   'about', 'chapter6',
   'ולמי שמוכן ללכת רחוק יותר - פתחנו דלת גם לעולם של אביזרי המין. בעדינות, בהדרגה, דרך מארזי תשוקה ומשחקים שיצרנו במיוחד למטרה הזו. תמיד באיכות. תמיד בטעם טוב. ותמיד ממקום שאנחנו עומדים מאחוריו - כי גם אנחנו עברנו את הדרך הזו.',
   'ולמי שמוכן ללכת רחוק יותר - פתחנו דלת גם לעולם של אביזרי המין. בעדינות, בהדרגה, דרך מארזי תשוקה ומשחקים שיצרנו במיוחד למטרה הזו. תמיד באיכות. תמיד בטעם טוב. ותמיד ממקום שאנחנו עומדים מאחוריו - כי גם אנחנו עברנו את הדרך הזו.',
   false),

  -- ── Chapter 7: The naming (brand keystone) ─────────────────────────
  ('about.founder.chapter7.title',
   'about', 'chapter7',
   'למה "מיאושי"?',
   'למה "מיאושי"?',
   false),
  ('about.founder.chapter7.lede',
   'about', 'chapter7',
   'השם "מיאושי" לא הומצא בחדר ישיבות, ולא נבחר על ידי משרד פרסום. הוא יצא מתוך הסיפור הכי אישי שלנו.',
   'השם "מיאושי" לא הומצא בחדר ישיבות, ולא נבחר על ידי משרד פרסום. הוא יצא מתוך הסיפור הכי אישי שלנו.',
   false),
  ('about.founder.chapter7.p1',
   'about', 'chapter7',
   'ארבע שנים מטריפות ביליתי באיטליה - עם אושרת, אשתי, שאז עוד הייתה החברה שלי. איטלקית - השפה הסקסית ביותר שיש - נכנסה לי לדם. כשחזרנו הביתה, היא נשארה איתנו. כינויי החיבה, המשפטים הקטנים, הצורה שבה קוראים לאהוב.',
   'ארבע שנים מטריפות ביליתי באיטליה - עם אושרת, אשתי, שאז עוד הייתה החברה שלי. איטלקית - השפה הסקסית ביותר שיש - נכנסה לי לדם. כשחזרנו הביתה, היא נשארה איתנו. כינויי החיבה, המשפטים הקטנים, הצורה שבה קוראים לאהוב.',
   false),
  ('about.founder.chapter7.p2',
   'about', 'chapter7',
   'וככה, בלי שתכננו, נבנה גם השם:',
   'וככה, בלי שתכננו, נבנה גם השם:',
   false),
  ('about.founder.chapter7.etymology.row1Italian',
   'about', 'chapter7',
   'Mio',
   'Mio',
   false),
  ('about.founder.chapter7.etymology.row1Meaning',
   'about', 'chapter7',
   'בְּאיטלקית: "שלי"',
   'בְּאיטלקית: "שלי"',
   false),
  ('about.founder.chapter7.etymology.row2Italian',
   'about', 'chapter7',
   'Oshi',
   'Oshi',
   false),
  ('about.founder.chapter7.etymology.row2Meaning',
   'about', 'chapter7',
   'הכינוי שלי לאהובתי, אושרת',
   'הכינוי שלי לאהובתי, אושרת',
   false),
  ('about.founder.chapter7.etymology.row3Italian',
   'about', 'chapter7',
   'Mio · Oshi',
   'Mio · Oshi',
   false),
  ('about.founder.chapter7.etymology.row3Meaning',
   'about', 'chapter7',
   '"אישה שלי" · "אושי שלי"',
   '"אישה שלי" · "אושי שלי"',
   false),
  ('about.founder.chapter7.etymology.brandLatin',
   'about', 'chapter7',
   'Mioshy',
   'Mioshy',
   false),
  ('about.founder.chapter7.etymology.brandHebrew',
   'about', 'chapter7',
   'מיאושי',
   'מיאושי',
   false),
  ('about.founder.chapter7.closer',
   'about', 'chapter7',
   'כל פעם שמישהו אומר את השם, הוא בעצם אומר את המשפט הכי אינטימי שיכול להיות בין שני אנשים - <em>אישה שלי</em>. וזה בדיוק מה שמיאושי עוסקת בו.',
   'כל פעם שמישהו אומר את השם, הוא בעצם אומר את המשפט הכי אינטימי שיכול להיות בין שני אנשים - <em>אישה שלי</em>. וזה בדיוק מה שמיאושי עוסקת בו.',
   true),

  -- ── Chapter 8: The invitation ──────────────────────────────────────
  ('about.founder.chapter8.title',
   'about', 'chapter8',
   'הסיפור הזה יכול להיות גם שלכם',
   'הסיפור הזה יכול להיות גם שלכם',
   false),
  ('about.founder.chapter8.p1',
   'about', 'chapter8',
   'מאהבה ותשוקה ענקיות, דרך הדעיכה שמביא איתו הזמן, ומשם - הצתה חוזרת של כל מה שהדליק אותנו פעם, באיטליה, בתחילת הדרך.',
   'מאהבה ותשוקה ענקיות, דרך הדעיכה שמביא איתו הזמן, ומשם - הצתה חוזרת של כל מה שהדליק אותנו פעם, באיטליה, בתחילת הדרך.',
   false),
  ('about.founder.chapter8.p2',
   'about', 'chapter8',
   'הסיפור הזה לא רק שלי. הוא של אלפי זוגות שעברו אותו דרך מיאושי. ובדיוק בשביל זה הקמתי את המקום הזה - כדי שלא תצטרכו לקרוא מאות ספרים, לעבור עשרות קורסים, ולעשות את הטעויות שאנחנו עשינו, לפני שתחזרו לעצמכם.',
   'הסיפור הזה לא רק שלי. הוא של אלפי זוגות שעברו אותו דרך מיאושי. ובדיוק בשביל זה הקמתי את המקום הזה - כדי שלא תצטרכו לקרוא מאות ספרים, לעבור עשרות קורסים, ולעשות את הטעויות שאנחנו עשינו, לפני שתחזרו לעצמכם.',
   false),
  ('about.founder.chapter8.p3',
   'about', 'chapter8',
   'אל תחיו "ליד".',
   'אל תחיו "ליד".',
   false),

  -- ── CTA + footer sign-off ──────────────────────────────────────────
  ('about.founder.cta.title',
   'about', 'cta',
   'עשו צעד גדול אל אהבה עוצמתית מחודשת.',
   'עשו צעד גדול אל אהבה עוצמתית מחודשת.',
   false),
  ('about.founder.cta.body',
   'about', 'cta',
   'הצטרפו אל מיאושי. הכלים שעזרו לנו, מחכים גם לכם.',
   'הצטרפו אל מיאושי. הכלים שעזרו לנו, מחכים גם לכם.',
   false),
  ('about.founder.cta.button',
   'about', 'cta',
   'התחילו את המסע שלכם',
   'Start your journey',
   false),
  ('about.founder.footer.signoff',
   'about', 'footer',
   E'באהבה,\nאיציק',
   E'באהבה,\nאיציק',
   false)
ON CONFLICT (key) DO NOTHING;

COMMIT;

NOTIFY pgrst, 'reload schema';
